# @format
bot:
  ID: '1338600733846802493'
  TOKEN: 'your_bot_token'
  PREFIX: '+'
  EMBED_COLOR: '#ff0000'
  OWNERS: ['1276162783188090955']
  MONGO: 'mongodb+srv://nishantchauhan04:11092004@cluster0.zmpu1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
links:
  INVITE: 'https://discord.com/oauth2/authorize?client_id=1338600733846802493'
  SUPPORT: 'https://discord.gg/m4pHHrnkxA'
  VOTE: ''